# see https://gohugo.io/getting-started/configuration/ for list of options
baseURL = "https://phpinternal.github.io/wiki/"
#relativeURLs = true
languageCode = "en-us"
title = "PHP RFC's"
theme = "php"
description	= "PHP Experimental Wiki Replacement"
timezone = "Europe/London"
footnoteReturnLinkContents = "^"
enableGitInfo = true
enableRobotsTXT = true

[params]
css = [ "css/wiki.css" ]
highlight = true
# highlightStyle = "solarized-dark"
highlightStyle = "github-gist"
highlightLanguages = ["php"]
githubRepository = "brzuchal/php-dev"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
status = "statuses"

[menu]
  [[menu.main]]
  identifier = "index"
  name = "Start"
  pre = "<i class='fa fa-home'></i>"
  url = "/"
  weight = -1000

  [[menu.main]]
  name = "RFC"
  post = "<i class='fa fa-check'></i>"
  url = "/rfc/"
  weight = -100

  [[menu.main]]
  name = "Pages"
  post = "<i class='fa fa-file'></i>"
  url = "/rfc/"
  weight = -100

  [[menu.icon]]
  url = "https://github.com/php/php-rfcs"
  name = "github"
  weight = 2

  [[menu.icon]]
  url = "https://twitter.com/official_php"
  name = "twitter"
  weight = 3
